object_type: global_settings
overrides:
    "xmla.auth.token.enabled": "true"
    "aggregate.speculative.enabled": "false"
    "sml.environment.variables" : 
      LABEL=Postgres
      CONNECTION="dev"
      DB_NAME="ATSCALE_SAMPLE_DATA"
      DB_SCHEMA="as_adventure"

