object_type: global_settings
overrides:
    "sml.validation.queries.enabled": "false"
    "xmla.auth.token.enabled": "true"
    "aggregate.speculative.enabled": "false"
    "aggregates.configuration.maximum_concurrent_materializations": 5
    "sml.environment.variables" : 
      LABEL="Postgres"
      CONNECTION="dev"
      DB_NAME="ATSCALE_SAMPLE_DATA"
      DB_SCHEMA="as_adventure"
      DB_NAME2="ATSCALE_SAMPLE_DATA"
      DB_SCHEMA2="as_adventure